# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: publish

env:
  JENKINS_VERSION: '2.426.2'
  NODE_MAJOR: '18'

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.1
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Setup Docker Buildx environment
        uses: docker/setup-buildx-action@v3.0.0
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          tags: mailsvb/jenkins:$JENKINS_VERSION
